[build-system]
requires = [ "setuptools" ]
build-backend = "setuptools.build_meta"

[project]
name = "maid"
description = "Helps me organize"
version = "1.0.0"
dependencies = [
    "pillow",
    "watchdog",
]
[project.scripts]
maid = "maid:main"